package hr.fer.zemris.java.custom.scripting.lexer;

/**
 * A class that represents a token generated by {@link SmartScriptLexer}.
 *
 * @param type  Type of the token.
 * @param value Value of the token.
 *
 * @see SmartScriptTokenType
 * @see SmartScriptLexer
 * @see SmartScriptLexerState
 * @see SmartScriptLexerException
 *
 * @author Marko Šelendić
 * @version 2.0
 */
public record SmartScriptToken(SmartScriptTokenType type, Object value) {
    /**
     * Creates a new token with the given type and value.
     *
     * @param type  type of the token
     * @param value value of the token
     */
    public SmartScriptToken {
    }

    /**
     * Returns the value of the token.
     *
     * @return value of the token
     */
    @Override
    public Object value() {
        return value;
    }

    /**
     * Returns the type of the token.
     *
     * @return type of the token
     */
    @Override
    public SmartScriptTokenType type() {
        return type;
    }
}
